name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd src && make
    - name: run
      run: cd src && make && ./bfc
    - name: make dump
      run: cd src && make && make dump
    - name: make clean
      run: cd src && make && make clean
